### ISSUE TITLE
Swap out SSH key steps with gh auth login

### ISSUE THREAD

**Issue by BuiltByWalsh** [BenGu3/dotfiles#1]
Cuz the `gh` cli is way cool :).

And I believe can be added to the `.Brewfile` with `brew "gh`.

**Comment by BenGu3** [comment]
Using 1Password SSH instead 👀 

https://github.com/BenGu3/dotfiles/blob/main/.ssh/config#L2
https://developer.1password.com/docs/ssh/get-started/
